sudo: false
language: cpp

addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.8
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
      - clang-3.8
      - g++-5
      - gcc-5
      - cmake
      - cmake-data
      - libxrandr-dev
      - libboost-dev
      - libiw-dev
      - libasound2-dev
      - libmpdclient-dev

install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
    - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.8" CC="clang-3.8"; fi

compiler:
  - clang
  - gcc

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_C_COMPILER="$CC" -DCMAKE_CXX_COMPILER="$CXX" .. && make
